### PR TITLE
Modified Databases, Model Name + Implement saving function + Complete View

### PR DESCRIPTION
**Pull request by darron1217**
Issue #3 

- Modified Databases, Model Names...etc
- Stablize Translation on Value
- Implement saving function
- Created/Modified some View
- Added Korean translation

I did some work on this plugin.
Now it seems to work on my project :)

Due to lack of undestanding about your intend, this PR needs some review...
So please check this PR and comment me if there's anything needs to be fixed :)

### CODE REVIEW

**Comment by nWidart** [comment]
Thanks! I'll try to review this when possible.

Did you upgrade the module work with version 3 of asgardcms?

**Comment by darron1217** [comment]
Yes, I did

composer.json
```json
{
	"name": "asgardcms/attribute-module",
	"description": "",
    "type": "asgard-module",
    "license": "MIT",
    "require": {
        "php": ">=7.0.0",
        "composer/installers": "~1.0",
        "idavoll/core-module": "~3.0"
    },
    "require-dev": {
        "phpunit/phpunit": "~6.0",
        "orchestra/testbench": "3.5.*"
    },
    "autoload-dev": {
        "psr-4": {
            "Modules\\Attribute\\": ".",
            "Modules\\": "Modules/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
	"authors": [
		{
			"name": "Nicolas Widart",
			"email": "n.widart@gmail.com"
		},
		{
			"name": "Darron Park",
			"email": "darron1217@gmail.com"
		}
	],
	"extra": {
        "laravel": {
            "providers": [
                "Modules\\Attribute\\Providers\\AttributeServiceProvider"
            ],
            "aliases": {

            }
        }
    },
	"autoload": {
		"psr-4": {
			"Modules\\Attribute\\": ""
		}
	}
}

```

**Comment by darron1217** [comment]
@nWidart 
Actually, I'm not good at writing Test Script...

So can you help me with fixing it?

**Comment by darron1217** [comment]
@nWidart 
Build fail error message says `Error: Class 'LaravelLocalization' not found`
Do you know how to fix it?

**Comment by darron1217** [comment]
I've fixed it :)

**Pull request closed without merging**
